<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="GET Feeds - Net Income Summary"
           tests="19"
           failures="14"
           errors="0"
           skipped="0"
           time="145.209">
  <properties />
            <testcase name="prepareAutomationReport" time="0.000" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.yodlee.insights.yodleeApi.utils.InsightsHelper.printSummaryOfTests(InsightsHelper.java:1966)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.prepareAutomationReport(TestGetInsightsForIncomeExpenseOverview.java:314)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="7.986" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="9.936" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="7.396" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="7.028" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="9.277" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.GeneratedMethodAccessor275.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="7.743" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="10.272" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="8.425" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="7.040" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="8.756" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="7.234" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="7.195" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="7.930" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  0 insights triggered But found 1 Insights for All Account "
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  0 insights triggered But found 1 Insights for All Account 
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview.testGetNotificationsForIncomeExpenseOverview(TestGetInsightsForIncomeExpenseOverview.java:307)
  sun.reflect.GeneratedMethodAccessor275.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="testGetNotificationsForIncomeExpenseOverview" time="6.636" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview" />
                <testcase name="testGetNotificationsForIncomeExpenseOverview" time="7.212" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview" />
                <testcase name="testGetNotificationsForIncomeExpenseOverview" time="7.410" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview" />
                <testcase name="testGetNotificationsForIncomeExpenseOverview" time="10.396" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview" />
                <testcase name="testGetNotificationsForIncomeExpenseOverview" time="7.337" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForIncomeExpenseOverview" />
      
</testsuite>
