<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="GET Feeds - Upcoming  Subscription"
           tests="30"
           failures="23"
           errors="0"
           skipped="0"
           time="1938.334">
  <properties />
            <testcase name="prepareAutomationReport" time="0.000" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.yodlee.insights.yodleeApi.utils.InsightsHelper.printSummaryOfTests(InsightsHelper.java:1966)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.prepareAutomationReport(TestGetInsightsForUpcomingSubscription.java:356)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.805" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.752" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.850" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.698" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.722" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.805" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.988" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  1 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  1 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.862" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.747" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.727" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:318)
  sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.836" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.833" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:318)
  sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="67.073" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="67.110" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:318)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.726" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.752" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:318)
  sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.762" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.825" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  6 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  6 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.701" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.708" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.813" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  8 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
            <testcase name="testGetNotificationsForUpcomingSubscription" time="67.008" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
                <failure type="java.lang.AssertionError"
                  message="Test FAILED -&gt; Expected  1 insights triggered But found Empty {}"
              >
<![CDATA[java.lang.AssertionError: Test FAILED -> Expected  1 insights triggered But found Empty {}
  org.testng.Assert.fail(Assert.java:94)
  com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="testGetNotificationsForUpcomingSubscription" time="66.880" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription" />
                <testcase name="testGetNotificationsForUpcomingSubscription" time="66.821" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription" />
                <testcase name="testGetNotificationsForUpcomingSubscription" time="67.036" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription" />
                <testcase name="testGetNotificationsForUpcomingSubscription" time="66.855" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription" />
                <testcase name="testGetNotificationsForUpcomingSubscription" time="66.801" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription" />
                <testcase name="testGetNotificationsForUpcomingSubscription" time="66.867" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription" />
                <testcase name="testGetNotificationsForUpcomingSubscription" time="66.971" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription" />
      
</testsuite>
