<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IN-L2504" ignored="0" name="GET Feeds - Upcoming  Subscription" tests="29" failures="22" timestamp="26 May 2021 12:25:37 GMT" time="2035.685" errors="0">
  <testcase name="@AfterMethod prepareAutomationReport" time="0.0" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.insights.yodleeApi.utils.InsightsHelper.printSummaryOfTests(InsightsHelper.java:1966)
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.prepareAutomationReport(TestGetInsightsForUpcomingSubscription.java:356)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod prepareAutomationReport -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.821" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.855" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.701" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.726" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.722" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.805" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.988" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  1 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  1 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.813" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="67.008" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  1 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  1 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.805" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="67.036" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.85" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.836" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.708" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="67.11" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.862" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.833" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.752" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.825" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  6 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  6 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.88" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.801" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.971" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
  <testcase name="testGetNotificationsForUpcomingSubscription" time="67.073" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.747" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.727" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.698" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.752" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.762" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription">
    <failure type="java.lang.AssertionError" message="Test FAILED -&amp;gt; Expected  8 insights triggered But found Empty {}">
      <![CDATA[java.lang.AssertionError: Test FAILED -> Expected  8 insights triggered But found Empty {}
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription.testGetNotificationsForUpcomingSubscription(TestGetInsightsForUpcomingSubscription.java:348)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForUpcomingSubscription -->
  <testcase name="testGetNotificationsForUpcomingSubscription" time="66.867" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForUpcomingSubscription"/>
</testsuite> <!-- GET Feeds - Upcoming  Subscription -->
