<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IN-L2504" ignored="0" name="Networth Summary" tests="14" failures="11" timestamp="18 May 2021 20:28:13 GMT" time="1038.041" errors="0">
  <testcase name="testGetNotificationsForNetworthSummary" time="156.889" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary"/>
  <testcase name="testGetNotificationsForNetworthSummary" time="91.942" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary"/>
  <testcase name="testGetNotificationsForNetworthSummary" time="61.582" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary">
    <failure type="java.lang.AssertionError" message="TEST FAILED">
      <![CDATA[java.lang.AssertionError: TEST FAILED
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary.testGetNotificationsForNetworthSummary(TestGetInsightsForNetworthSummary.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNetworthSummary -->
  <testcase name="testGetNotificationsForNetworthSummary" time="61.639" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary">
    <failure type="java.lang.AssertionError" message="TEST FAILED">
      <![CDATA[java.lang.AssertionError: TEST FAILED
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary.testGetNotificationsForNetworthSummary(TestGetInsightsForNetworthSummary.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNetworthSummary -->
  <testcase name="testGetNotificationsForNetworthSummary" time="61.55" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary">
    <failure type="java.lang.AssertionError" message="TEST FAILED">
      <![CDATA[java.lang.AssertionError: TEST FAILED
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary.testGetNotificationsForNetworthSummary(TestGetInsightsForNetworthSummary.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNetworthSummary -->
  <testcase name="testGetNotificationsForNetworthSummary" time="61.548" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary">
    <failure type="java.lang.AssertionError" message="TEST FAILED">
      <![CDATA[java.lang.AssertionError: TEST FAILED
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary.testGetNotificationsForNetworthSummary(TestGetInsightsForNetworthSummary.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNetworthSummary -->
  <testcase name="testGetNotificationsForNetworthSummary" time="61.56" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary">
    <failure type="java.lang.AssertionError" message="TEST FAILED">
      <![CDATA[java.lang.AssertionError: TEST FAILED
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary.testGetNotificationsForNetworthSummary(TestGetInsightsForNetworthSummary.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNetworthSummary -->
  <testcase name="testGetNotificationsForNetworthSummary" time="61.638" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary">
    <failure type="java.lang.AssertionError" message="TEST FAILED">
      <![CDATA[java.lang.AssertionError: TEST FAILED
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary.testGetNotificationsForNetworthSummary(TestGetInsightsForNetworthSummary.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNetworthSummary -->
  <testcase name="testGetNotificationsForNetworthSummary" time="61.803" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary">
    <failure type="java.lang.AssertionError" message="TEST FAILED">
      <![CDATA[java.lang.AssertionError: TEST FAILED
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary.testGetNotificationsForNetworthSummary(TestGetInsightsForNetworthSummary.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNetworthSummary -->
  <testcase name="testGetNotificationsForNetworthSummary" time="61.64" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary">
    <failure type="java.lang.AssertionError" message="TEST FAILED">
      <![CDATA[java.lang.AssertionError: TEST FAILED
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary.testGetNotificationsForNetworthSummary(TestGetInsightsForNetworthSummary.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNetworthSummary -->
  <testcase name="testGetNotificationsForNetworthSummary" time="61.572" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary">
    <failure type="java.lang.AssertionError" message="TEST FAILED">
      <![CDATA[java.lang.AssertionError: TEST FAILED
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary.testGetNotificationsForNetworthSummary(TestGetInsightsForNetworthSummary.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNetworthSummary -->
  <testcase name="testGetNotificationsForNetworthSummary" time="61.644" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary">
    <failure type="java.lang.AssertionError" message="TEST FAILED">
      <![CDATA[java.lang.AssertionError: TEST FAILED
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary.testGetNotificationsForNetworthSummary(TestGetInsightsForNetworthSummary.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNetworthSummary -->
  <testcase name="testGetNotificationsForNetworthSummary" time="61.637" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary">
    <failure type="java.lang.AssertionError" message="TEST FAILED">
      <![CDATA[java.lang.AssertionError: TEST FAILED
	at com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary.testGetNotificationsForNetworthSummary(TestGetInsightsForNetworthSummary.java:298)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- testGetNotificationsForNetworthSummary -->
  <testcase name="testGetNotificationsForNetworthSummary" time="92.065" classname="com.yodlee.app.yodleeApi.Insights.Notifications.V2.TestGetInsightsForNetworthSummary"/>
</testsuite> <!-- Networth Summary -->
